# Generated by Django 4.2.5 on 2023-11-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_user_address_user_description_user_name_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./'),
        ),
    ]
